version: '3'

services:
  trenit:
    image: trenipy
    container_name: trenipy
    working_dir: /app
    command: python ./main.py
    volumes:
      - ./:/app
    depends_on:
      - db
    restart: always

  db:
    image: mariadb
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PWD
      - MYSQL_DATABASE=$MYSQL_DB
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - db_vol:/var/lib/mysql
    restart: always

  phpadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - PMA_HOST=$MYSQL_DB
      # DON'T SET THESE TWO VARIABLES HERE IN PRODUCTION
      - PMA_USER=$MYSQL_USER
      - PMA_PASSWORD=$MYSQL_PASSWORD
    depends_on:
      - db

volumes:
  db_vol:

