version: '3'

services:
  trenit:
    image: trenipy
    container_name: trenipy
    working_dir: /app
    command: python ./main.py
    volumes:
      - ./:/app
    restart: always

#  db:
#    image: mariadb
#    container_name: db
#    volumes:
#      - db_vol:/var/lib/mysql

volumes:
  db_vol:

