import unittest
from telegram_bot.utils.pdf_extraction import extract_info_from_text, train_info_pattern
from telegram_bot.utils.structs import Train
import datetime


class TestPdfExtraction(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.text1 = ' \n \n \n \nCIV Carrier 0420 - Partita Iva: 05403151420\nIssuer 0420\nData Emissione 04/02/2019 ore 15:45\nCanale: Internet B2C\nRicevuta n. 680745420 del 04/02/2019\n \n \nAVVERTENZE\n1. Valgono le condizioni di trasporto del Vettore che effettua il servizio. Per Trenitalia valgono le Condizioni Generali di Trasporto dei Passeggeri consultabili sul sito www.trenitalia.com\ned in biglietteria, nonché le regole uniformi CIV.\n2. Il biglietto regionale acquistato online è nominativo, personale e incedibile. Il cambio nominativo non è ammesso.\n3. Il biglietto regionale acquistato online è già convalidato con la data e ora di partenza del treno prescelto all\'atto dell\'acquisto e riportate sul biglietto. Consente di viaggiare dall\'ora di\npartenza riportata sul biglietto e nelle  4 ore successive.\n4. Il biglietto regionale acquistato online deve essere esibito da supporto informatico (pc, tablet, smartphone) in grado di consentire la corretta visualizzazione di file in .pdf o codice\nAztec/QRCode oppure mostrando il biglietto dall\'area riservata ne "I Miei Viaggi" disponibile su App Trenitalia, www.trenitalia.com e Mobile o su supporto cartaceo, unitamente ad un\nvalido documento di riconoscimento, ad ogni richiesta del personale di controlleria. In mancanza di anche uno solo dei due, il viaggiatore viene considerato come sprovvisto di biglietto\ne regolarizzato in base alla normativa vigente.\n5. Cambio data/ora e Rimborso possibili entro le ore 23:59 del giorno precedente la partenza, salvo diverse disposizioni, presso: Biglietterie, Self Service (non per il rimborso), App\nTrenitalia, www.trenitalia.com e Agenzie di Viaggio emittenti.\n6. Per tutto quanto non specificato si rimanda alle Condizioni Generali di Trasporto dei Passeggeri di Trenitalia.\n \n \n \n \n \nPer informazioni, acquisti e modifiche al biglietto: vai su www.trenitalia.com, scarica la nostra App Trenitalia o chiama il Call Center al numero 892021 (numero a pagamento)\n \nVIAGGIO da Pomezia-S. Palomba a Roma Termini \nValido per 4 ore a partire dalle 16:05  del  04/02/2019\nCodice Biglietto: 1052114420\nStazione di Partenza\n \nPomezia-S. Palomba\nOre 16:05 - 04/02/2019\nStazione di Arrivo\n \nRoma Termini\nOre 16:24 - 04/02/2019\nTreno: Regionale 12218\nServizio: 2° Classe\n* Importo pagato totale: 2.10 €\n* Il corrispettivo pagato è relativo ad operazioni assoggettate ad I.V.A\nNon valido ai fini fiscali\nDETTAGLIO PASSEGGERI\nNome Passeggero (Adulto)\nMARIO ROSSI\nOfferta - Servizio\n  CartaFreccia\n  Punti\nORDINARIA - 2ª CLASSE\n  174837420\n  4,20\nAcquirente: MARIO ROSSI\nPagamento: Utilizzo carta di credito/debito o carta prepagata\nPagina 1 di 1\n'
        cls.text2 = " \n \n \n \nCIV Carrier 0420  - Partita Iva: 05403151420\nIssuer 0420\nData Emissione 24/02/2019 ore 11:00\nCanale: Internet B2C\nNumero Titolo: 1064583420\nVIAGGIO da Pisa Centrale a Roma Termini il 28/02/2019 alle ore 14:07\nPNR: U6U420\n \n \nCONDIZIONI DI TRASPORTO\nValgono le condizioni di trasporto del vettore (carrier).  Le condizioni che regolano il servizio di trasporto ferroviario con Trenitalia sono disponibili sul sito www.trenitalia.com, presso le\nbiglietterie Trenitalia e presso le agenzie di viaggio.  Per consentire di registrare la tua presenza, comunica il PNR al personale di bordo. La mancata comunicazione del PNR equivale\nal mancato possesso del biglietto.\n \n \n \ncirca 33 Kg\n \nPer informazioni, acquisti e modifiche al biglietto: vai su www.trenitalia.com, scarica la nostra App Trenitalia o chiama il Call Center al numero 892021 (numero a pagamento)\n \nStazione di Partenza\n \nPisa Centrale\nOre 14:07 - 28/02/2019\nStazione di Arrivo\n \nRoma Termini\nOre 17:03 - 28/02/2019\nTreno:  FrecciaBianca 8613\nServizio: 2° Classe \nCarrozza:  7\nPosti: 11D\nImporto totale*: 24.90 €\n* Il corrispettivo pagato è relativo ad operazioni assoggettate ad I.V.A\nNon valido ai fini fiscali\n \n \nDETTAGLIO PASSEGGERI\nNome Passeggero (Adulto)\nMARIO ROSSI\nOfferta - Servizio\nCodice CP\nCartaFreccia\nPunti\nSuper Economy-2ª\nCLASSE\n0\n13B\n994420\n174837420\n58,420\n \nSuper Economy: Biglietto non modificabile e non rimborsabile. Soggetto a disponibilita'\nposti\n \nAcquirente: MARIO ROSSI\nPagamento: PayPal\n \n \nLe porte del treno si chiudono\n1 minuto prima della partenza\nPagina 1 di 2\n"

    def test_regex_match(self):
        self.assertIsNotNone(train_info_pattern.search(self.text1))
        self.assertIsNotNone(train_info_pattern.search(self.text2))

    def test_extract_info_from_text(self):
        train1 = extract_info_from_text(self.text1, "")
        train2 = extract_info_from_text(self.text2, "")
        self.assertEqual(train1, Train(id=-1, code='12218', depart_stat='S09150', depart_date=datetime.datetime(2019, 2, 4, 16, 5), user='', checked=0, check_daily=False, check_interval=None, coach=None, seat=None))
        self.assertEqual(train2, Train(id=-1, code='8613', depart_stat='S04700', depart_date=datetime.datetime(2019, 2, 28, 14, 7), user='', checked=0, check_daily=False, check_interval=None, coach='7', seat='11D'))
