drake_approving = "CAADBAADtAYAAolcjAwGES5fk4AYpwI"
blackman_crying = "CAADBAADHAADL_yJIGlxuTtVE1TNAg"
destruction_100 = "CAADAgADEgIAApLXlAhR4Zo3-FNMXQI"
tom_puzzled = "CAADBAADJQ0AAufo-wL2uHDEfdtM1gI"
tom_not_understanding = "CAADBAADLw0AAufo-wIT8-RSXaqXsQI"
sad_cat = "CAADAQADT2UAAiO2xw4bHz6bD0ZKeAI"
tick = "☑"
toninelli = "CAADBAADSwADGcfiDZZbhnP-SZ6tAg"
